export const FORM_20 = {
  id: 'FORM_20',
  department: 'ພະແນກຈັດຕັ້ງ-ບຸກຄະລາກອນ',
  name: 'ແບບຟອມສະໝັກເຂົ້າເຮັດວຽກ',
  templatePath: '/templates/20. ແບບຟອມສະໝັກເຂົ້າເຮັດວຽກ (13).pdf',
  fields: [
    { id: 'pos_applying', type: 'text', label: 'ຕຳແໜ່ງທີ່ສະໝັກ (Position Applied For)', pageIndex: 0, x: 270, y: 673, section: '1. ຂໍ້ມູນການສະໝັກ', placeholder: 'ພະນັກງານການຕະຫຼາດ', colSpan: 2 },
    { id: 'first_name', type: 'text', label: 'ຊື່ (First Name)', pageIndex: 0, x: 130, y: 634, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', placeholder: 'ຕົວຢ່າງ: ສຸດາ', required: true },
    { id: 'last_name', type: 'text', label: 'ນາມສະກຸນ (Last Name)', pageIndex: 0, x: 29, y: 470, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', placeholder: 'ຕົວຢ່າງ: ສີສຸວັນ', required: true },
    { id: 'dob', type: 'date', label: 'ວັນເດືອນປີເກີດ (Date of Birth)', pageIndex: 0, x: 112, y: 613, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'age', type: 'text', label: 'ອາຍຸ (Age)', pageIndex: 0, x: 320, y: 609, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'birth_village', type: 'text', label: 'ບ້ານເກີດ (Village)', pageIndex: 0, x: 160, y: 661, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'birth_district', type: 'text', label: 'ເມືອງເກີດ (District)', pageIndex: 0, x: 340, y: 661, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'birth_province', type: 'text', label: 'ແຂວງເກີດ (Province)', pageIndex: 0, x: 460, y: 661, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'curr_village', type: 'text', label: 'ບ້ານປັດຈຸບັນ (Village)', pageIndex: 0, x: 160, y: 640, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'curr_district', type: 'text', label: 'ເມືອງປັດຈຸບັນ (District)', pageIndex: 0, x: 340, y: 640, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'curr_province', type: 'text', label: 'ແຂວງປັດຈຸບັນ (Province)', pageIndex: 0, x: 460, y: 640, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'phone', type: 'text', label: 'ເບີໂທຕິດຕໍ່ (Telephone)', pageIndex: 0, x: 160, y: 619, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', required: true },
    { id: 'email', type: 'text', label: 'ອີເມລ (E-Mail Address)', pageIndex: 0, x: 340, y: 619, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'sex', type: 'text', label: 'ເພດ (Sex)', pageIndex: 0, x: 74, y: 596, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'nationality', type: 'text', label: 'ສັນຊາດ (Nationality)', pageIndex: 0, x: 67, y: 470, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'ethnicity', type: 'text', label: 'ຊົນເຜົ່າ (Ethnicity)', pageIndex: 0, x: 113, y: 472, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'religion', type: 'text', label: 'ສາສະໜາ (Religion)', pageIndex: 0, x: 156, y: 474, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'marital_single', type: 'checkbox', label: 'ໂສດ (Single)', pageIndex: 0, x: 438, y: 598, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'marital_married', type: 'checkbox', label: 'ແຕ່ງງານ (Married)', pageIndex: 0, x: 462, y: 598, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'marital_widow', type: 'checkbox', label: 'ໝ້າຍ (Widow)', pageIndex: 0, x: 487, y: 598, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'marital_divorced', type: 'checkbox', label: 'ຢ່າຮ້າງ (Divorced)', pageIndex: 0, x: 512, y: 598, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'motorbike_yes', type: 'checkbox', label: 'ສາມາດຂັບຈັກ ໄດ້ / Yes', pageIndex: 0, x: 118, y: 568, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'motorbike_no', type: 'checkbox', label: 'ສາມາດຂັບຈັກ ບໍ່ໄດ້ / No', pageIndex: 0, x: 145, y: 568, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'motorbike_lic_yes', type: 'checkbox', label: 'ໃບຂັບຂີ່ຈັກ ມີ / Yes', pageIndex: 0, x: 280, y: 568, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'motorbike_lic_no', type: 'checkbox', label: 'ໃບຂັບຂີ່ຈັກ ບໍ່ມີ / No', pageIndex: 0, x: 305, y: 568, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_yes', type: 'checkbox', label: 'ສາມາດຂັບລົດ ໄດ້ / Yes', pageIndex: 0, x: 118, y: 553, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_no', type: 'checkbox', label: 'ສາມາດຂັບລົດ ບໍ່ໄດ້ / No', pageIndex: 0, x: 145, y: 553, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_lic_yes', type: 'checkbox', label: 'ໃບຂັບຂີ່ລົດ ມີ / Yes', pageIndex: 0, x: 280, y: 553, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_lic_no', type: 'checkbox', label: 'ໃບຂັບຂີ່ລົດ ບໍ່ມີ / No', pageIndex: 0, x: 305, y: 553, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_lic_type', type: 'text', label: 'ປະເພດໃບຂັບຂີ່ (Driving Permission Type)', pageIndex: 0, x: 380, y: 553, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'edu1_school', type: 'text', label: 'ສະຖານທີ່ຮຽນ 1 (Place of Graduation)', pageIndex: 0, x: 45, y: 497, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu1_degree', type: 'text', label: 'ລະດັບ 1 (Degree)', pageIndex: 0, x: 215, y: 497, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu1_major', type: 'text', label: 'ສາຂາ 1 (Majored in)', pageIndex: 0, x: 305, y: 497, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu1_year', type: 'text', label: 'ປີຈົບ 1 (Year of Graduation)', pageIndex: 0, x: 430, y: 497, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'train1_topic', type: 'text', label: 'ຫົວຂໍ້ຝຶກ 1 (Topic)', pageIndex: 0, x: 45, y: 423, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train1_by', type: 'text', label: 'ຈັດໂດຍ 1 (Conducted by)', pageIndex: 0, x: 175, y: 423, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train1_date', type: 'text', label: 'ວັນທີ 1 (Training Date)', pageIndex: 0, x: 285, y: 423, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train1_place', type: 'text', label: 'ສະຖານທີ່ 1 (Training Place)', pageIndex: 0, x: 395, y: 423, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'com_word_vgood', type: 'checkbox', label: 'Word (ດີຫຼາຍ)', pageIndex: 0, x: 238, y: 375, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'lang_eng_read_good', type: 'checkbox', label: 'Eng Read (Good)', pageIndex: 1, x: 177, y: 743, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'special_skills', type: 'textarea', label: 'ຄວາມສາມາດພິເສດ (Special Skills)', pageIndex: 1, x: 42, y: 630, section: '10. ຄວາມສາມາດພິເສດ' },
    { id: 'emp1_company', type: 'text', label: 'ຊື່ບໍລິສັດ 1 (Company)', pageIndex: 1, x: 42, y: 596, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_start_date', type: 'text', label: 'ວ.ດ.ປ ເຂົ້າເຮັດວຽກ 1', pageIndex: 1, x: 120, y: 596, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_end_date', type: 'text', label: 'ວ.ດ.ປ ອອກວຽກ 1', pageIndex: 1, x: 200, y: 596, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_pos', type: 'text', label: 'ຕຳແໜ່ງ 1 (Position)', pageIndex: 1, x: 270, y: 596, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_salary', type: 'text', label: 'ເງິນເດືອນ 1 (Salary)', pageIndex: 1, x: 360, y: 596, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_reason', type: 'text', label: 'ເຫດຜົນທີ່ອອກ 1', pageIndex: 1, x: 420, y: 596, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emg1_name', type: 'text', label: 'ຊື່-ບານສະກຸນ 1', pageIndex: 1, x: 80, y: 462, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'emg1_address', type: 'text', label: 'ທີ່ອຍູ່ 1 (Address)', pageIndex: 1, x: 200, y: 462, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'emg1_phone', type: 'text', label: 'ເບີໂທສຸກເສີນ 1 (Phone)', pageIndex: 1, x: 330, y: 462, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ', required: true },
    { id: 'emg1_relation', type: 'text', label: 'ຄວາມສຳພັນ 1', pageIndex: 1, x: 435, y: 462, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'applicant_resume', type: 'file_multiple', label: 'ເອກະສານຄັດຕິດ ອື່ນໆ (CV, ໃບປະກາດ ຯລຯ)', pageIndex: 1, x: 0, y: 0, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: false },
    { id: 'applicant_signature', type: 'file_signature', label: 'ຮູບລາຍເຊັນ / Signature', pageIndex: 1, x: 0, y: 0, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: true },
    { id: 'sign_date', type: 'date', label: 'ວັນທີສະໝັກ (Date Applied)', pageIndex: 1, x: 120, y: 355, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ' }
  ]
};
