export const FORM_20 = {
  id: 'FORM_20',
  department: 'ພະແນກຈັດຕັ້ງ-ບຸກຄະລາກອນ',
  name: 'ແບບຟອມສະໝັກເຂົ້າເຮັດວຽກ',
  templatePath: '/templates/20. ແບບຟອມສະໝັກເຂົ້າເຮັດວຽກ (13).pdf',
  fields: [
    { id: 'pos_applying', type: 'text', label: 'ຕຳແໜ່ງທີ່ສະໝັກ (Position Applied For)', pageIndex: 0.0, x: 273, y: 677, section: '1. ຂໍ້ມູນການສະໝັກ', placeholder: 'ພະນັກງານການຕະຫຼາດ', colSpan: 2 },
    { id: 'first_name', type: 'text', label: 'ຊື່ (First Name)', pageIndex: 0.0, x: 138, y: 634, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', placeholder: 'ຕົວຢ່າງ: ສຸດາ', required: true },
    { id: 'last_name', type: 'text', label: 'ນາມສະກຸນ (Last Name)', pageIndex: 0.0, x: 436, y: 634, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', placeholder: 'ຕົວຢ່າງ: ສີສຸວັນ', required: true },
    { id: 'dob', type: 'text', placeholder: 'ຕົວຢ່າງ: 25/12/1995', label: 'ວັນເດືອນປີເກີດ (Date of Birth)', pageIndex: 0.0, x: 176, y: 613, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'age', type: 'text', placeholder: 'ຕົວຢ່າງ: 25 ປີ', label: 'ອາຍຸ (Age)', pageIndex: 0.0, x: 320, y: 609, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'birth_village', type: 'text', placeholder: 'ຕົວຢ່າງ: ໂພນສິນວນ', label: 'ບ້ານເກີດ (Village)', pageIndex: 0.0, x: 174, y: 580, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 3 },
    { id: 'birth_district', type: 'text', placeholder: 'ຕົວຢ່າງ: ສີສັດຕະນາກ', label: 'ເມືອງເກີດ (District)', pageIndex: 0.0, x: 324, y: 580, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 3 },
    { id: 'birth_province', type: 'text', placeholder: 'ຕົວຢ່າງ: ນະຄອນຫຼວງວຽງຈັນ', label: 'ແຂວງເກີດ (Province)', pageIndex: 0.0, x: 492, y: 580, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 3 },
    { id: 'curr_village', type: 'text', placeholder: 'ຕົວຢ່າງ: ໂພນສິນວນ', label: 'ບ້ານປັດຈຸບັນ (Village)', pageIndex: 0.0, x: 173, y: 551, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 3 },
    { id: 'curr_district', type: 'text', placeholder: 'ຕົວຢ່າງ: ສີສັດຕະນາກ', label: 'ເມືອງປັດຈຸບັນ (District)', pageIndex: 0.0, x: 324, y: 551, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 3 },
    { id: 'curr_province', type: 'text', placeholder: 'ຕົວຢ່າງ: ນະຄອນຫຼວງວຽງຈັນ', label: 'ແຂວງປັດຈຸບັນ (Province)', pageIndex: 0.0, x: 492, y: 551, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 3 },
    { id: 'phone', type: 'text', placeholder: 'ຕົວຢ່າງ: 020 5555 5555', label: 'ເບີໂທຕິດຕໍ່ (Telephone)', pageIndex: 0.0, x: 149, y: 526, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', required: true },
    { id: 'email', type: 'text', placeholder: 'ຕົວຢ່າງ: name@gmail.com', label: 'ອີເມລ (E-Mail Address)', pageIndex: 0.0, x: 374, y: 528, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'applicant_photo', type: 'file_photo', label: 'ຮູບຜູ້ສະໝັກ 3x4 / Photo 3x4', pageIndex: 0.0, x: 462, y: 698, maxWidth: 90, maxHeight: 120, section: '1. ຂໍ້ມູນການສະໝັກ', required: false },
    { id: 'sex', type: 'select', options: [{ label: '♂️ ຊາຍ', value: 'ຊາຍ' }, { label: '♀️ ຍິງ', value: 'ຍິງ' }, { label: '⚧️ ອື່ນໆ', value: 'ອື່ນໆ' }], placeholder: 'ເລືອກເພດ...', label: 'ເພດ (Sex)', pageIndex: 0.0, x: 41, y: 474, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 4 },
    { id: 'nationality', type: 'text', placeholder: 'ຕົວຢ່າງ: ລາວ', label: 'ສັນຊາດ (Nationality)', pageIndex: 0.0, x: 116, y: 475, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 4 },
    { id: 'ethnicity', type: 'text', placeholder: 'ຕົວຢ່າງ: ລາວລຸ່ມ', label: 'ຊົນເຜົ່າ (Ethnicity)', pageIndex: 0.0, x: 183, y: 474, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 4 },
    { id: 'religion', type: 'text', placeholder: 'ຕົວຢ່າງ: ພຸດ', label: 'ສາສະໜາ (Religion)', pageIndex: 0.0, x: 245, y: 475, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ', colSpan: 4 },
    { id: 'marital_single', type: 'checkbox', label: 'ໂສດ (Single)', pageIndex: 0.0, x: 316, y: 468, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'marital_married', type: 'checkbox', label: 'ແຕ່ງງານ (Married)', pageIndex: 0.0, x: 389, y: 467, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'marital_widow', type: 'checkbox', label: 'ໝ້າຍ (Widow)', pageIndex: 0.0, x: 463, y: 465, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'marital_divorced', type: 'checkbox', label: 'ຢ່າຮ້າງ (Divorced)', pageIndex: 0.0, x: 540, y: 464, section: '2. ຂໍ້ມູນທົ່ວໄປຂອງຜູ້ສະໝັກ' },
    { id: 'motorbike_yes', type: 'checkbox', label: 'ສາມາດຂັບຈັກ ໄດ້ / Yes', pageIndex: 0.0, x: 164, y: 429, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'motorbike_no', type: 'checkbox', label: 'ສາມາດຂັບຈັກ ບໍ່ໄດ້ / No', pageIndex: 0.0, x: 223, y: 430, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'motorbike_lic_yes', type: 'checkbox', label: 'ໃບຂັບຂີ່ຈັກ ມີ / Yes', pageIndex: 0.0, x: 425, y: 430, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'motorbike_lic_no', type: 'checkbox', label: 'ໃບຂັບຂີ່ຈັກ ບໍ່ມີ / No', pageIndex: 0.0, x: 480, y: 432, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_yes', type: 'checkbox', label: 'ສາມາດຂັບລົດ ໄດ້ / Yes', pageIndex: 0.0, x: 165, y: 403, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_no', type: 'checkbox', label: 'ສາມາດຂັບລົດ ບໍ່ໄດ້ / No', pageIndex: 0.0, x: 222, y: 403, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_lic_yes', type: 'checkbox', label: 'ໃບຂັບຂີ່ລົດ ມີ / Yes', pageIndex: 0.0, x: 424, y: 411, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_lic_no', type: 'checkbox', label: 'ໃບຂັບຂີ່ລົດ ບໍ່ມີ / No', pageIndex: 0.0, x: 481, y: 409, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'car_lic_type', type: 'text', label: 'ປະເພດໃບຂັບຂີ່ (Driving Permission Type)', pageIndex: 0.0, x: 469, y: 395, section: '3. ຄວາມສາມາດໃນການຂັບຂີ່' },
    { id: 'edu1_school', type: 'text', label: 'ສະຖານທີ່ຮຽນ 1 (Place of Graduation)', pageIndex: 0.0, x: 51, y: 325, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu2_school', type: 'text', label: 'ສະຖານທີ່ຮຽນ 1 (Place of Graduation)', pageIndex: 0.0, x: 51, y: 307, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu3_school', type: 'text', label: 'ສະຖານທີ່ຮຽນ 1 (Place of Graduation)', pageIndex: 0.0, x: 51, y: 289, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu1_degree', type: 'text', label: 'ລະດັບ 1 (Degree)', pageIndex: 0.0, x: 263, y: 323, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu2_degree', type: 'text', label: 'ລະດັບ 1 (Degree)', pageIndex: 0.0, x: 263, y: 305, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu3_degree', type: 'text', label: 'ລະດັບ 1 (Degree)', pageIndex: 0.0, x: 263, y: 287, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu1_major', type: 'text', label: 'ສາຂາ 1 (Majored in)', pageIndex: 0.0, x: 395, y: 320, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu2_major', type: 'text', label: 'ສາຂາ 1 (Majored in)', pageIndex: 0.0, x: 395, y: 302, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu3_major', type: 'text', label: 'ສາຂາ 1 (Majored in)', pageIndex: 0.0, x: 395, y: 284, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu1_year', type: 'text', label: 'ປີຈົບ 1 (Year of Graduation)', pageIndex: 0.0, x: 493, y: 320, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu2_year', type: 'text', label: 'ປີຈົບ 1 (Year of Graduation)', pageIndex: 0.0, x: 493, y: 302, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'edu3_year', type: 'text', label: 'ປີຈົບ 1 (Year of Graduation)', pageIndex: 0.0, x: 493, y: 284, section: '6. ປະຫວັດການສຶກສາ' },
    { id: 'train1_topic', type: 'text', label: 'ຫົວຂໍ້ຝຶກ 1 (Topic)', pageIndex: 0.0, x: 48, y: 237, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train2_topic', type: 'text', label: 'ຫົວຂໍ້ຝຶກ 1 (Topic)', pageIndex: 0.0, x: 48, y: 219, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train3_topic', type: 'text', label: 'ຫົວຂໍ້ຝຶກ 1 (Topic)', pageIndex: 0.0, x: 48, y: 201, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train1_by', type: 'text', label: 'ຈັດໂດຍ 1 (Conducted by)', pageIndex: 0.0, x: 167, y: 235, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train2_by', type: 'text', label: 'ຈັດໂດຍ 1 (Conducted by)', pageIndex: 0.0, x: 167, y: 217, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train3_by', type: 'text', label: 'ຈັດໂດຍ 1 (Conducted by)', pageIndex: 0.0, x: 167, y: 199, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train1_date', type: 'text', label: 'ວັນທີ 1 (Training Date)', pageIndex: 0.0, x: 311, y: 236, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train2_date', type: 'text', label: 'ວັນທີ 1 (Training Date)', pageIndex: 0.0, x: 311, y: 218, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train3_date', type: 'text', label: 'ວັນທີ 1 (Training Date)', pageIndex: 0.0, x: 311, y: 200, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train1_place', type: 'text', label: 'ສະຖານທີ່ 1 (Training Place)', pageIndex: 0.0, x: 445, y: 235, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train2_place', type: 'text', label: 'ສະຖານທີ່ 1 (Training Place)', pageIndex: 0.0, x: 445, y: 217, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'train3_place', type: 'text', label: 'ສະຖານທີ່ 1 (Training Place)', pageIndex: 0.0, x: 445, y: 199, section: '7. ການຝຶກອົບຮົມ' },
    { id: 'com_word_vgood', type: 'checkbox', label: 'Word (ດີຫຼາຍ)', pageIndex: 0.0, x: 337, y: 146, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_word_good', type: 'checkbox', label: 'Com Word Good', pageIndex: 0, x: 439, y: 145, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_word_weak', type: 'checkbox', label: 'Com Word Weak', pageIndex: 0, x: 535, y: 145, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_excel_vgood', type: 'checkbox', label: 'Com Excel Vgood', pageIndex: 0, x: 338, y: 125, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_excel_good', type: 'checkbox', label: 'Com Excel Good', pageIndex: 0, x: 439, y: 126, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_excel_weak', type: 'checkbox', label: 'Com Excel Weak', pageIndex: 0, x: 536, y: 121, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_ppt_vgood', type: 'checkbox', label: 'Com Ppt Vgood', pageIndex: 0, x: 338, y: 103, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_ppt_good', type: 'checkbox', label: 'Com Ppt Good', pageIndex: 0, x: 440, y: 102, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_ppt_weak', type: 'checkbox', label: 'Com Ppt Weak', pageIndex: 0, x: 535, y: 99, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_others_name', type: 'text', label: 'ໂປຣແກຣມອື່ນໆ (ລະບຸ)', pageIndex: 0, x: 110, y: 78, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_oth_vgood', type: 'checkbox', label: 'Com Oth Vgood', pageIndex: 0, x: 337, y: 79, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_oth_good', type: 'checkbox', label: 'Com Oth Good', pageIndex: 0, x: 439, y: 76, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'com_oth_weak', type: 'checkbox', label: 'Com Oth Weak', pageIndex: 0, x: 536, y: 71, section: '8. ທັກສະຄອມພິວເຕີ' },
    { id: 'lang_eng_read_good', type: 'checkbox', label: 'Eng Read (Good)', pageIndex: 1.0, x: 166, y: 750, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_read_fair', type: 'checkbox', label: 'Lang Eng Read Fair', pageIndex: 1, x: 213, y: 750, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_read_weak', type: 'checkbox', label: 'Lang Eng Read Weak', pageIndex: 1, x: 262, y: 749, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_write_good', type: 'checkbox', label: 'Lang Eng Write Good', pageIndex: 1, x: 313, y: 748, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_write_fair', type: 'checkbox', label: 'Lang Eng Write Fair', pageIndex: 1, x: 362, y: 750, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_write_weak', type: 'checkbox', label: 'Lang Eng Write Weak', pageIndex: 1, x: 407, y: 750, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_speak_good', type: 'checkbox', label: 'Lang Eng Speak Good', pageIndex: 1, x: 450, y: 749, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_speak_fair', type: 'checkbox', label: 'Lang Eng Speak Fair', pageIndex: 1, x: 498, y: 750, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_eng_speak_weak', type: 'checkbox', label: 'Lang Eng Speak Weak', pageIndex: 1, x: 555, y: 750, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_read_good', type: 'checkbox', label: 'Lang Chi Read Good', pageIndex: 1, x: 166, y: 735, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_read_fair', type: 'checkbox', label: 'Lang Chi Read Fair', pageIndex: 1, x: 213, y: 735, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_read_weak', type: 'checkbox', label: 'Lang Chi Read Weak', pageIndex: 1, x: 263, y: 733, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_write_good', type: 'checkbox', label: 'Lang Chi Write Good', pageIndex: 1, x: 313, y: 733, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_write_fair', type: 'checkbox', label: 'Lang Chi Write Fair', pageIndex: 1, x: 362, y: 734, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_write_weak', type: 'checkbox', label: 'Lang Chi Write Weak', pageIndex: 1, x: 408, y: 733, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_speak_good', type: 'checkbox', label: 'Lang Chi Speak Good', pageIndex: 1, x: 451, y: 731, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_speak_fair', type: 'checkbox', label: 'Lang Chi Speak Fair', pageIndex: 1, x: 498, y: 731, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_chi_speak_weak', type: 'checkbox', label: 'Lang Chi Speak Weak', pageIndex: 1, x: 555, y: 732, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_read_good', type: 'checkbox', label: 'Lang Vie Read Good', pageIndex: 1, x: 166, y: 720, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_read_fair', type: 'checkbox', label: 'Lang Vie Read Fair', pageIndex: 1, x: 213, y: 720, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_read_weak', type: 'checkbox', label: 'Lang Vie Read Weak', pageIndex: 1, x: 263, y: 719, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_write_good', type: 'checkbox', label: 'Lang Vie Write Good', pageIndex: 1, x: 313, y: 718, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_write_fair', type: 'checkbox', label: 'Lang Vie Write Fair', pageIndex: 1, x: 362, y: 717, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_write_weak', type: 'checkbox', label: 'Lang Vie Write Weak', pageIndex: 1, x: 407, y: 716, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_speak_good', type: 'checkbox', label: 'Lang Vie Speak Good', pageIndex: 1, x: 451, y: 714, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_speak_fair', type: 'checkbox', label: 'Lang Vie Speak Fair', pageIndex: 1, x: 498, y: 712, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_vie_speak_weak', type: 'checkbox', label: 'Lang Vie Speak Weak', pageIndex: 1, x: 555, y: 716, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_read_good', type: 'checkbox', label: 'Lang Hmo Read Good', pageIndex: 1, x: 166, y: 705, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_read_fair', type: 'checkbox', label: 'Lang Hmo Read Fair', pageIndex: 1, x: 213, y: 705, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_read_weak', type: 'checkbox', label: 'Lang Hmo Read Weak', pageIndex: 1, x: 262, y: 705, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_write_good', type: 'checkbox', label: 'Lang Hmo Write Good', pageIndex: 1, x: 314, y: 703, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_write_fair', type: 'checkbox', label: 'Lang Hmo Write Fair', pageIndex: 1, x: 362, y: 703, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_write_weak', type: 'checkbox', label: 'Lang Hmo Write Weak', pageIndex: 1, x: 407, y: 701, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_speak_good', type: 'checkbox', label: 'Lang Hmo Speak Good', pageIndex: 1, x: 451, y: 699, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_speak_fair', type: 'checkbox', label: 'Lang Hmo Speak Fair', pageIndex: 1, x: 499, y: 696, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_hmo_speak_weak', type: 'checkbox', label: 'Lang Hmo Speak Weak', pageIndex: 1, x: 555, y: 703, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_others_name', type: 'text', label: 'ພາສາອື່ນໆ (ລະບຸ)', pageIndex: 1, x: 126, y: 686, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_read_good', type: 'checkbox', label: 'Lang Oth Read Good', pageIndex: 1, x: 166, y: 686, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_read_fair', type: 'checkbox', label: 'Lang Oth Read Fair', pageIndex: 1, x: 214, y: 687, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_read_weak', type: 'checkbox', label: 'Lang Oth Read Weak', pageIndex: 1, x: 263, y: 690, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_write_good', type: 'checkbox', label: 'Lang Oth Write Good', pageIndex: 1, x: 314, y: 688, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_write_fair', type: 'checkbox', label: 'Lang Oth Write Fair', pageIndex: 1, x: 363, y: 688, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_write_weak', type: 'checkbox', label: 'Lang Oth Write Weak', pageIndex: 1, x: 408, y: 685, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_speak_good', type: 'checkbox', label: 'Lang Oth Speak Good', pageIndex: 1, x: 451, y: 684, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_speak_fair', type: 'checkbox', label: 'Lang Oth Speak Fair', pageIndex: 1, x: 499, y: 682, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'lang_oth_speak_weak', type: 'checkbox', label: 'Lang Oth Speak Weak', pageIndex: 1, x: 556, y: 684, section: '9. ຄວາມສາມາດທາງດ້ານພາສາ' },
    { id: 'special_skills', type: 'textarea', label: 'ຄວາມສາມາດພິເສດ (Special Skills)', pageIndex: 1.0, x: 42, y: 630, section: '10. ຄວາມສາມາດພິເສດ' },
    { id: 'emp1_company', type: 'text', label: 'ຊື່ບໍລິສັດ 1 (Company)', pageIndex: 1.0, x: 47, y: 520, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp2_company', type: 'text', label: 'ຊື່ບໍລິສັດ 1 (Company)', pageIndex: 1.0, x: 47, y: 455, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_start_date', type: 'text', label: 'ວ.ດ.ປ ເຂົ້າເຮັດວຽກ 1', pageIndex: 1.0, x: 119, y: 521, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp2_start_date', type: 'text', label: 'ວ.ດ.ປ ເຂົ້າເຮັດວຽກ 1', pageIndex: 1.0, x: 119, y: 456, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_end_date', type: 'text', label: 'ວ.ດ.ປ ອອກວຽກ 1', pageIndex: 1.0, x: 206, y: 519, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp2_end_date', type: 'text', label: 'ວ.ດ.ປ ອອກວຽກ 1', pageIndex: 1.0, x: 206, y: 454, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_pos', type: 'text', label: 'ຕຳແໜ່ງ 1 (Position)', pageIndex: 1.0, x: 303, y: 520, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp2_pos', type: 'text', label: 'ຕຳແໜ່ງ 1 (Position)', pageIndex: 1.0, x: 303, y: 455, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_salary', type: 'text', label: 'ເງິນເດືອນ 1 (Salary)', pageIndex: 1.0, x: 409, y: 520, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp2_salary', type: 'text', label: 'ເງິນເດືອນ 1 (Salary)', pageIndex: 1.0, x: 409, y: 455, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_reason', type: 'text', label: 'ເຫດຜົນທີ່ອອກ 1', pageIndex: 1.0, x: 487, y: 520, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp1_desc', type: 'text', pageIndex: 1, x: 120, y: 495, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp2_reason', type: 'text', label: 'ເຫດຜົນທີ່ອອກ 1', pageIndex: 1.0, x: 487, y: 455, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emp2_desc', type: 'text', pageIndex: 1, x: 120, y: 430, section: '11. ປະສົບການເຮັດວຽກ' },
    { id: 'emg1_name', type: 'text', label: 'ຊື່-ບານສະກຸນ 1', pageIndex: 1.0, x: 47, y: 364, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'emg1_name', type: 'text', label: 'ຊື່-ບານສະກຸນ 1', pageIndex: 1.0, x: 47, y: 364, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'emg1_address', type: 'text', label: 'ທີ່ອຍູ່ 1 (Address)', pageIndex: 1.0, x: 201, y: 363, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'emg1_address', type: 'text', label: 'ທີ່ອຍູ່ 1 (Address)', pageIndex: 1.0, x: 201, y: 363, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'emg1_relation', type: 'text', label: 'ຄວາມສຳພັນ 1', pageIndex: 1.0, x: 488, y: 365, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'emg1_relation', type: 'text', label: 'ຄວາມສຳພັນ 2', pageIndex: 1.0, x: 488, y: 365, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'applicant_resume', type: 'file_multiple', label: 'ເອກະສານຄັດຕິດ ອື່ນໆ (CV, ໃບປະກາດ ຯລຯ)', pageIndex: 1.0, x: 0, y: 0, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: false },
    { id: 'applicant_signature', type: 'file_signature', label: 'ຮູບລາຍເຊັນ / Signature', pageIndex: 1.0, x: 0, y: 0, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: true },
    { id: 'sign_date', type: 'text', placeholder: 'ຕົວຢ່າງ: 01/04/2006', label: 'ວັນທີສະໝັກ (Date Applied)', pageIndex: 1.0, x: 481, y: 273, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ' }
  ]
};
