const FORM_20 = {
  id: 'FORM_20',
  department: 'ພະແນກຈັດຕັ້ງ-ບຸກຄະລາກອນ',
  name: 'ແບບຟອມສະໝັກເຂົ້າເຮັດວຽກ',
  templatePath: 'templates/form_template.pdf',
  fields: [
    { id: 'pos_applying', type: 'text', pageIndex: 0, x: 270, y: 673 },
    { id: 'first_name', type: 'text', pageIndex: 0, x: 128, y: 631 },
    { id: 'last_name', type: 'text', pageIndex: 0, x: 433, y: 631 },
    { id: 'dob', type: 'date', pageIndex: 0, x: 170, y: 611, x_month: 199, x_year: 225 },
    { id: 'age', type: 'text', pageIndex: 0, x: 520, y: 606 },
    { id: 'birth_village', type: 'text', pageIndex: 0, x: 165, y: 577 },
    { id: 'birth_district', type: 'text', pageIndex: 0, x: 318, y: 577 },
    { id: 'birth_province', type: 'text', pageIndex: 0, x: 489, y: 577 },
    { id: 'curr_village', type: 'text', pageIndex: 0, x: 167, y: 548 },
    { id: 'curr_district', type: 'text', pageIndex: 0, x: 318, y: 548 },
    { id: 'curr_province', type: 'text', pageIndex: 0, x: 490, y: 548 },
    { id: 'phone', type: 'text', pageIndex: 0, x: 144, y: 523 },
    { id: 'email', type: 'text', pageIndex: 0, x: 372, y: 524 },
    { id: 'applicant_photo', type: 'file_photo', pageIndex: 0, x: 480, y: 790, maxWidth: 90, maxHeight: 100 },
    { id: 'sex', type: 'text', pageIndex: 0, x: 39, y: 468 },
    { id: 'nationality', type: 'text', pageIndex: 0, x: 105, y: 468 },
    { id: 'ethnicity', type: 'text', pageIndex: 0, x: 175, y: 468 },
    { id: 'religion', type: 'text', pageIndex: 0, x: 245, y: 468 },
    { id: 'marital_single', type: 'checkbox', pageIndex: 0, x: 312, y: 460 },
    { id: 'marital_married', type: 'checkbox', pageIndex: 0, x: 384, y: 460 },
    { id: 'marital_widow', type: 'checkbox', pageIndex: 0, x: 458, y: 460 },
    { id: 'marital_divorced', type: 'checkbox', pageIndex: 0, x: 534, y: 460 },
    { id: 'motorbike_yes', type: 'checkbox', pageIndex: 0, x: 160, y: 426 },
    { id: 'motorbike_no', type: 'checkbox', pageIndex: 0, x: 217, y: 426 },
    { id: 'motorbike_lic_yes', type: 'checkbox', pageIndex: 0, x: 420, y: 426 },
    { id: 'motorbike_lic_no', type: 'checkbox', pageIndex: 0, x: 479, y: 426 },
    { id: 'car_yes', type: 'checkbox', pageIndex: 0, x: 160, y: 400 },
    { id: 'car_no', type: 'checkbox', pageIndex: 0, x: 218, y: 400 },
    { id: 'car_lic_yes', type: 'checkbox', pageIndex: 0, x: 420, y: 407 },
    { id: 'car_lic_no', type: 'checkbox', pageIndex: 0, x: 480, y: 407 },
    { id: 'car_lic_type', type: 'text', pageIndex: 0, x: 469, y: 392 },
    { id: 'edu1_school', type: 'text', pageIndex: 0, x: 35, y: 320, maxWidth: 180, multiline: true, maxLines: 2 },
    { id: 'edu2_school', type: 'text', pageIndex: 0, x: 35, y: 302, maxWidth: 180, multiline: true, maxLines: 2 },
    { id: 'edu3_school', type: 'text', pageIndex: 0, x: 35, y: 284, maxWidth: 180, multiline: true, maxLines: 2 },
    { id: 'edu1_degree', type: 'text', pageIndex: 0, x: 258, y: 320, maxWidth: 100, multiline: true, maxLines: 2 },
    { id: 'edu2_degree', type: 'text', pageIndex: 0, x: 258, y: 302, maxWidth: 100, multiline: true, maxLines: 2 },
    { id: 'edu3_degree', type: 'text', pageIndex: 0, x: 258, y: 284, maxWidth: 100, multiline: true, maxLines: 2 },
    { id: 'edu1_major', type: 'text', pageIndex: 0, x: 380, y: 320, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'edu2_major', type: 'text', pageIndex: 0, x: 380, y: 302, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'edu3_major', type: 'text', pageIndex: 0, x: 380, y: 284, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'edu1_year', type: 'text', pageIndex: 0, x: 485, y: 320, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'edu2_year', type: 'text', pageIndex: 0, x: 485, y: 302, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'edu3_year', type: 'text', pageIndex: 0, x: 485, y: 284, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'train1_topic', type: 'text', pageIndex: 0, x: 33, y: 232, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'train2_topic', type: 'text', pageIndex: 0, x: 33, y: 216, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'train3_topic', type: 'text', pageIndex: 0, x: 33, y: 198, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'train1_by', type: 'text', pageIndex: 0, x: 156, y: 232, maxWidth: 120, multiline: true, maxLines: 2 },
    { id: 'train2_by', type: 'text', pageIndex: 0, x: 156, y: 216, maxWidth: 120, multiline: true, maxLines: 2 },
    { id: 'train3_by', type: 'text', pageIndex: 0, x: 156, y: 198, maxWidth: 120, multiline: true, maxLines: 2 },
    { id: 'train1_date', type: 'text', pageIndex: 0, x: 310, y: 232, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'train2_date', type: 'text', pageIndex: 0, x: 310, y: 216, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'train3_date', type: 'text', pageIndex: 0, x: 310, y: 198, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'train1_place', type: 'text', pageIndex: 0, x: 432, y: 232, maxWidth: 140, multiline: true, maxLines: 2 },
    { id: 'train2_place', type: 'text', pageIndex: 0, x: 432, y: 216, maxWidth: 140, multiline: true, maxLines: 2 },
    { id: 'train3_place', type: 'text', pageIndex: 0, x: 432, y: 198, maxWidth: 140, multiline: true, maxLines: 2 },
    { id: 'com_word_vgood', type: 'checkbox', pageIndex: 0, x: 333, y: 142 },
    { id: 'com_word_good', type: 'checkbox', pageIndex: 0, x: 433, y: 142 },
    { id: 'com_word_weak', type: 'checkbox', pageIndex: 0, x: 530, y: 142 },
    { id: 'com_excel_vgood', type: 'checkbox', pageIndex: 0, x: 333, y: 120 },
    { id: 'com_excel_good', type: 'checkbox', pageIndex: 0, x: 433, y: 120 },
    { id: 'com_excel_weak', type: 'checkbox', pageIndex: 0, x: 530, y: 120 },
    { id: 'com_ppt_vgood', type: 'checkbox', pageIndex: 0, x: 333, y: 97 },
    { id: 'com_ppt_good', type: 'checkbox', pageIndex: 0, x: 434, y: 97 },
    { id: 'com_ppt_weak', type: 'checkbox', pageIndex: 0, x: 530, y: 97 },
    { id: 'com_others_name', type: 'text', pageIndex: 0, x: 94, y: 75 },
    { id: 'com_oth_vgood', type: 'checkbox', pageIndex: 0, x: 333, y: 73 },
    { id: 'com_oth_good', type: 'checkbox', pageIndex: 0, x: 434, y: 73 },
    { id: 'com_oth_weak', type: 'checkbox', pageIndex: 0, x: 530, y: 73 },
    { id: 'lang_eng_read_good', type: 'checkbox', pageIndex: 1, x: 160, y: 744 },
    { id: 'lang_eng_read_fair', type: 'checkbox', pageIndex: 1, x: 208, y: 744 },
    { id: 'lang_eng_read_weak', type: 'checkbox', pageIndex: 1, x: 258, y: 744 },
    { id: 'lang_eng_write_good', type: 'checkbox', pageIndex: 1, x: 308, y: 744 },
    { id: 'lang_eng_write_fair', type: 'checkbox', pageIndex: 1, x: 358, y: 744 },
    { id: 'lang_eng_write_weak', type: 'checkbox', pageIndex: 1, x: 404, y: 744 },
    { id: 'lang_eng_speak_good', type: 'checkbox', pageIndex: 1, x: 446, y: 744 },
    { id: 'lang_eng_speak_fair', type: 'checkbox', pageIndex: 1, x: 493, y: 744 },
    { id: 'lang_eng_speak_weak', type: 'checkbox', pageIndex: 1, x: 550, y: 744 },
    { id: 'lang_chi_read_good', type: 'checkbox', pageIndex: 1, x: 160, y: 728 },
    { id: 'lang_chi_read_fair', type: 'checkbox', pageIndex: 1, x: 208, y: 728 },
    { id: 'lang_chi_read_weak', type: 'checkbox', pageIndex: 1, x: 258, y: 728 },
    { id: 'lang_chi_write_good', type: 'checkbox', pageIndex: 1, x: 308, y: 728 },
    { id: 'lang_chi_write_fair', type: 'checkbox', pageIndex: 1, x: 358, y: 728 },
    { id: 'lang_chi_write_weak', type: 'checkbox', pageIndex: 1, x: 404, y: 728 },
    { id: 'lang_chi_speak_good', type: 'checkbox', pageIndex: 1, x: 446, y: 728 },
    { id: 'lang_chi_speak_fair', type: 'checkbox', pageIndex: 1, x: 493, y: 728 },
    { id: 'lang_chi_speak_weak', type: 'checkbox', pageIndex: 1, x: 550, y: 728 },
    { id: 'lang_vie_read_good', type: 'checkbox', pageIndex: 1, x: 160, y: 714 },
    { id: 'lang_vie_read_fair', type: 'checkbox', pageIndex: 1, x: 208, y: 714 },
    { id: 'lang_vie_read_weak', type: 'checkbox', pageIndex: 1, x: 258, y: 714 },
    { id: 'lang_vie_write_good', type: 'checkbox', pageIndex: 1, x: 308, y: 714 },
    { id: 'lang_vie_write_fair', type: 'checkbox', pageIndex: 1, x: 358, y: 714 },
    { id: 'lang_vie_write_weak', type: 'checkbox', pageIndex: 1, x: 404, y: 714 },
    { id: 'lang_vie_speak_good', type: 'checkbox', pageIndex: 1, x: 446, y: 714 },
    { id: 'lang_vie_speak_fair', type: 'checkbox', pageIndex: 1, x: 493, y: 714 },
    { id: 'lang_vie_speak_weak', type: 'checkbox', pageIndex: 1, x: 550, y: 714 },
    { id: 'lang_hmo_read_good', type: 'checkbox', pageIndex: 1, x: 160, y: 698 },
    { id: 'lang_hmo_read_fair', type: 'checkbox', pageIndex: 1, x: 208, y: 698 },
    { id: 'lang_hmo_read_weak', type: 'checkbox', pageIndex: 1, x: 258, y: 698 },
    { id: 'lang_hmo_write_good', type: 'checkbox', pageIndex: 1, x: 308, y: 698 },
    { id: 'lang_hmo_write_fair', type: 'checkbox', pageIndex: 1, x: 358, y: 698 },
    { id: 'lang_hmo_write_weak', type: 'checkbox', pageIndex: 1, x: 404, y: 698 },
    { id: 'lang_hmo_speak_good', type: 'checkbox', pageIndex: 1, x: 446, y: 698 },
    { id: 'lang_hmo_speak_fair', type: 'checkbox', pageIndex: 1, x: 493, y: 698 },
    { id: 'lang_hmo_speak_weak', type: 'checkbox', pageIndex: 1, x: 550, y: 698 },
    { id: 'lang_others_name', type: 'text', pageIndex: 1, x: 112, y: 681, size: 8, maxWidth: 30 },
    { id: 'lang_oth_read_good', type: 'checkbox', pageIndex: 1, x: 160, y: 682 },
    { id: 'lang_oth_read_fair', type: 'checkbox', pageIndex: 1, x: 208, y: 682 },
    { id: 'lang_oth_read_weak', type: 'checkbox', pageIndex: 1, x: 258, y: 682 },
    { id: 'lang_oth_write_good', type: 'checkbox', pageIndex: 1, x: 308, y: 682 },
    { id: 'lang_oth_write_fair', type: 'checkbox', pageIndex: 1, x: 358, y: 682 },
    { id: 'lang_oth_write_weak', type: 'checkbox', pageIndex: 1, x: 404, y: 682 },
    { id: 'lang_oth_speak_good', type: 'checkbox', pageIndex: 1, x: 446, y: 682 },
    { id: 'lang_oth_speak_fair', type: 'checkbox', pageIndex: 1, x: 493, y: 682 },
    { id: 'lang_oth_speak_weak', type: 'checkbox', pageIndex: 1, x: 550, y: 682 },
    { id: 'special_skills', type: 'text', pageIndex: 1, x: 30, y: 634, maxWidth: 550, multiline: true, maxLines: 4 },
    { id: 'emp1_company', type: 'text', pageIndex: 1, x: 34, y: 516, maxWidth: 60, multiline: true, maxLines: 2 },
    { id: 'emp2_company', type: 'text', pageIndex: 1, x: 34, y: 457, maxWidth: 60, multiline: true, maxLines: 2 },
    { id: 'emp1_start_date', type: 'text', pageIndex: 1, x: 105, y: 516, maxWidth: 75, multiline: true, maxLines: 2 },
    { id: 'emp2_start_date', type: 'text', pageIndex: 1, x: 105, y: 457, maxWidth: 75, multiline: true, maxLines: 2 },
    { id: 'emp1_end_date', type: 'text', pageIndex: 1, x: 190, y: 516, maxWidth: 85, multiline: true, maxLines: 2 },
    { id: 'emp2_end_date', type: 'text', pageIndex: 1, x: 190, y: 457, maxWidth: 85, multiline: true, maxLines: 2 },
    { id: 'emp1_pos', type: 'text', pageIndex: 1, x: 290, y: 516, maxWidth: 95, multiline: true, maxLines: 2 },
    { id: 'emp2_pos', type: 'text', pageIndex: 1, x: 290, y: 457, maxWidth: 95, multiline: true, maxLines: 2 },
    { id: 'emp1_salary', type: 'text', pageIndex: 1, x: 400, y: 516, maxWidth: 65, multiline: true, maxLines: 2 },
    { id: 'emp2_salary', type: 'text', pageIndex: 1, x: 385, y: 457, maxWidth: 65, multiline: true, maxLines: 2 },
    { id: 'emp1_reason', type: 'text', pageIndex: 1, x: 475, y: 516, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'emp1_desc', type: 'text', pageIndex: 1, x: 110, y: 495, maxWidth: 450, multiline: true, maxLines: 2 },
    { id: 'emp2_reason', type: 'text', pageIndex: 1, x: 475, y: 457, maxWidth: 90, multiline: true, maxLines: 2 },
    { id: 'emp2_desc', type: 'text', pageIndex: 1, x: 110, y: 438, maxWidth: 450, multiline: true, maxLines: 2 },
    { id: 'emg1_name', type: 'text', pageIndex: 1, x: 32, y: 363, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'emg2_name', type: 'text', pageIndex: 1, x: 32, y: 344, maxWidth: 115, multiline: true, maxLines: 2 },
    { id: 'emg1_address', type: 'text', pageIndex: 1, x: 190, y: 363, maxWidth: 170, multiline: true, maxLines: 2 },
    { id: 'emg2_address', type: 'text', pageIndex: 1, x: 190, y: 344, maxWidth: 170, multiline: true, maxLines: 2 },
    { id: 'emg1_phone', type: 'text', pageIndex: 1, x: 370, y: 363, maxWidth: 95, multiline: true, maxLines: 2 },
    { id: 'emg2_phone', type: 'text', pageIndex: 1, x: 370, y: 344, maxWidth: 95, multiline: true, maxLines: 2 },
    { id: 'emg1_relation', type: 'text', label: 'ຄວາມສຳພັນ 1', pageIndex: 1, x: 480, y: 363, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ', maxWidth: 80, multiline: true, maxLines: 2 },
    { id: 'emg2_relation', type: 'text', label: 'ຄວາມສຳພັນ 2', pageIndex: 1, x: 480, y: 344, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ', maxWidth: 80, multiline: true, maxLines: 2 },
    { id: 'applicant_resume', type: 'file_multiple', label: 'ເອກະສານຄັດຕິດ ອື່ນໆ', pageIndex: 1, x: 0, y: 0, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: false },
    { id: 'applicant_signature', type: 'file_signature', label: 'ຮູບລາຍເຊັນ', pageIndex: 1, x: 390, y: 210, maxWidth: 150, maxHeight: 45, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: true },
    { id: 'sign_date', type: 'date', label: 'ວັນທີສະໝັກ (Date Applied)', pageIndex: 1, x: 35, y: 255, x_month: 75, x_year: 110, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ' }
  ]
};

module.exports = { FORM_20 };
