const FORM_20 = {
  id: 'FORM_20',
  department: 'ພະແນກຈັດຕັ້ງ-ບຸກຄະລາກອນ',
  name: 'ແບບຟອມສະໝັກເຂົ້າເຮັດວຽກ',
  templatePath: 'templates/form_template.pdf',
  fields: [
    { id: 'pos_applying', type: 'text', pageIndex: 0, x: 270, y: 673 },
    { id: 'first_name', type: 'text', pageIndex: 0, x: 130, y: 634 },
    { id: 'last_name', type: 'text', pageIndex: 0, x: 29, y: 470 },
    { id: 'dob', type: 'date', pageIndex: 0, x: 112, y: 613 },
    { id: 'age', type: 'text', pageIndex: 0, x: 320, y: 609 },
    { id: 'birth_village', type: 'text', pageIndex: 0, x: 160, y: 661 },
    { id: 'birth_district', type: 'text', pageIndex: 0, x: 340, y: 661 },
    { id: 'birth_province', type: 'text', pageIndex: 0, x: 460, y: 661 },
    { id: 'curr_village', type: 'text', pageIndex: 0, x: 160, y: 640 },
    { id: 'curr_district', type: 'text', pageIndex: 0, x: 340, y: 640 },
    { id: 'curr_province', type: 'text', pageIndex: 0, x: 460, y: 640 },
    { id: 'phone', type: 'text', pageIndex: 0, x: 160, y: 619 },
    { id: 'email', type: 'text', pageIndex: 0, x: 340, y: 619 },
    { id: 'sex', type: 'text', pageIndex: 0, x: 74, y: 596 },
    { id: 'nationality', type: 'text', pageIndex: 0, x: 67, y: 470 },
    { id: 'ethnicity', type: 'text', pageIndex: 0, x: 113, y: 472 },
    { id: 'religion', type: 'text', pageIndex: 0, x: 156, y: 474 },
    // Simplified backend mapped coordinates
    { id: 'marital_single', type: 'checkbox', pageIndex: 0, x: 438, y: 598 },
    { id: 'marital_married', type: 'checkbox', pageIndex: 0, x: 462, y: 598 },
    { id: 'marital_widow', type: 'checkbox', pageIndex: 0, x: 487, y: 598 },
    { id: 'marital_divorced', type: 'checkbox', pageIndex: 0, x: 512, y: 598 },
    { id: 'motorbike_yes', type: 'checkbox', pageIndex: 0, x: 118, y: 568 },
    { id: 'motorbike_no', type: 'checkbox', pageIndex: 0, x: 145, y: 568 },
    { id: 'motorbike_lic_yes', type: 'checkbox', pageIndex: 0, x: 280, y: 568 },
    { id: 'motorbike_lic_no', type: 'checkbox', pageIndex: 0, x: 305, y: 568 },
    { id: 'car_yes', type: 'checkbox', pageIndex: 0, x: 118, y: 553 },
    { id: 'car_no', type: 'checkbox', pageIndex: 0, x: 145, y: 553 },
    { id: 'car_lic_yes', type: 'checkbox', pageIndex: 0, x: 280, y: 553 },
    { id: 'car_lic_no', type: 'checkbox', pageIndex: 0, x: 305, y: 553 },
    { id: 'car_lic_type', type: 'text', pageIndex: 0, x: 380, y: 553 },
    
    // Page 2 specific mappings
    { id: 'edu1_school', type: 'text', pageIndex: 0, x: 45, y: 497 },
    { id: 'edu1_degree', type: 'text', pageIndex: 0, x: 215, y: 497 },
    { id: 'edu1_major', type: 'text', pageIndex: 0, x: 305, y: 497 },
    { id: 'edu1_year', type: 'text', pageIndex: 0, x: 430, y: 497 },
    { id: 'train1_topic', type: 'text', pageIndex: 0, x: 45, y: 423 },
    { id: 'train1_by', type: 'text', pageIndex: 0, x: 175, y: 423 },
    { id: 'train1_date', type: 'text', pageIndex: 0, x: 285, y: 423 },
    { id: 'train1_place', type: 'text', pageIndex: 0, x: 395, y: 423 },
    { id: 'com_word_vgood', type: 'checkbox', pageIndex: 0, x: 238, y: 375 },
    { id: 'lang_eng_read_good', type: 'checkbox', pageIndex: 1, x: 177, y: 743 },
    { id: 'special_skills', type: 'text', pageIndex: 1, x: 42, y: 630 },
    { id: 'emp1_company', type: 'text', pageIndex: 1, x: 42, y: 596 },
    { id: 'emp1_start_date', type: 'text', pageIndex: 1, x: 120, y: 596 },
    { id: 'emp1_end_date', type: 'text', pageIndex: 1, x: 200, y: 596 },
    { id: 'emp1_pos', type: 'text', pageIndex: 1, x: 270, y: 596 },
    { id: 'emp1_salary', type: 'text', pageIndex: 1, x: 360, y: 596 },
    { id: 'emp1_reason', type: 'text', pageIndex: 1, x: 420, y: 596 },
    { id: 'emg1_name', type: 'text', pageIndex: 1, x: 80, y: 462 },
    { id: 'emg1_address', type: 'text', pageIndex: 1, x: 200, y: 462 },
    { id: 'emg1_relation', type: 'text', label: 'ຄວາມສຳພັນ 1', pageIndex: 1, x: 435, y: 462, section: '12. ບຸກຄົນອ້າງອີງ/ສຸກເສີນ' },
    { id: 'applicant_resume', type: 'file_multiple', label: 'ເອກະສານຄັດຕິດ ອື່ນໆ (CV, ໃບປະກາດ ຯລຯ)', pageIndex: 1, x: 0, y: 0, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: false },
    { id: 'applicant_signature', type: 'file_signature', label: 'ຮູບລາຍເຊັນ / Signature', pageIndex: 1, x: 0, y: 0, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ', required: true },
    { id: 'sign_date', type: 'date', label: 'ວັນທີສະໝັກ (Date Applied)', pageIndex: 1, x: 120, y: 355, section: '13. ເອກະສານ ແລະ ການຢືນຢັນ' },
  ]
};

module.exports = { FORM_20 };
